import os
import io
import traceback
import asyncio
import duckdb
import discord
from discord.ext import commands, tasks
from google import genai
from google.genai import types

# Import the ingestion function from ingest.py
try:
    import ingest
except ImportError:
    ingest = None

# ---------------------------------------------------------
# Environment & Client Initialization
# ---------------------------------------------------------
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
DB_PATH = os.getenv("DUCKDB_PATH", "nfl_stats.duckdb")

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix="!", intents=intents)

ai_client = genai.Client(api_key=GEMINI_API_KEY)


# ---------------------------------------------------------
# Database Tool for Gemini
# ---------------------------------------------------------
def run_sql_query(sql_query: str) -> list[dict]:
    """Execute a read-only DuckDB SQL query against NFL statistics.

    Available Tables:
    1. weekly_stats:
       - player_id, player_display_name, position, team, season, week
       - targets, receptions, receiving_yards, receiving_tds, target_share, air_yards_share
       - carries, rushing_yards, rushing_tds, fantasy_points, fantasy_points_ppr
       - completions, attempts, passing_yards, passing_tds, interceptions

    2. rosters:
       - season, team, position, depth_chart_position, jersey_number, status, full_name, gsis_id

    3. play_by_play:
       - play_id, game_id, season, week, posteam, defteam, yardline_100, down, ydstogo, play_type
       - yards_gained, shotgun, no_huddle, qb_dropback, pass, rush, air_yards, yards_after_catch
       - epa, wpa, passer_player_id, passer_player_name, receiver_player_id, receiver_player_name
       - rusher_player_id, rusher_player_name, qb_kneel, qb_spike, play_description
    
    4. schedule:
        - game_id, season, game_type, week, gameday, weekday, gametime
        -  away_team, home_team, away_score, home_score, result, spread_line, total_line
    
    """

    clean_query = sql_query.strip()
    print(f"\n[SQL GENERATED BY GEMINI]:\n{clean_query}\n", flush=True)
    if not clean_query.lower().startswith("select"):
        return [{"error": "Only SELECT queries are permitted."}]

    try:
        # Open in read-only mode so concurrent bot commands do not lock the DB
        con = duckdb.connect(DB_PATH, read_only=True)
        results = con.execute(clean_query).df().to_dict(orient="records")
        con.close()
        print(f"[SQL RESULTS COUNT]: {len(results)} rows returned", flush=True)
        if results:
            print(f"[SQL SAMPLE ROW]: {results[0]}", flush=True)
        return results[:50]  # Limit records to protect prompt context
    except Exception as e:
        print(f"[SQL ERROR]: {e}", flush=True)
        return [{"error": f"SQL execution error: {str(e)}"}]


# ---------------------------------------------------------
# Gemini Orchestration
# ---------------------------------------------------------
def ask_gemini_with_duckdb(user_prompt: str) -> str:
    """Synchronous worker that feeds the prompt and DuckDB tool to Gemini."""
    system_instruction=(
        "You are Hank 2.0, an expert NFL statistics and fantasy football analyst with direct access "
        "to a local DuckDB database containing three tables: `weekly_stats`, `rosters`, and `play_by_play`.\n\n"
        "Table Selection & Routing Guidelines:\n"
        "1. `weekly_stats`: Use for player season/weekly production, leaderboards, and fantasy totals (PPR/standard).\n"
        "2. `rosters`: Use for checking depth charts, active roster status, and looking up player `gsis_id`.\n"
        "3. `play_by_play`: Use for down-and-distance splits, EPA/efficiency, formations (shotgun), and ANY defensive matchups or performance against positions.\n\n"
        "4. `schedules`: Future matchups, remaining games, and schedule calendars.\n\n"
        "Rest-of-Season (ROS) & Matchup Analysis Rules:\n"
        "- Linking Players to Schedules:\n"
        "  * Individual players belong to a team via `rosters.team` (e.g., 'DAL', 'DET').\n"
        "  * To find upcoming games for players, join `rosters` to `schedules` matching either home or away:\n"
        "    JOIN schedules s ON (r.team = s.home_team OR r.team = s.away_team)\n"
        "- Determining the Opponent:\n"
        "  * For each scheduled matchup, identify the opponent using:\n"
        "    CASE WHEN s.home_team = r.team THEN s.away_team ELSE s.home_team END AS opponent_team\n"
        "- Filter Future Weeks:\n"
        "  * Always restrict schedule lookups to remaining games: `WHERE s.week > [current_completed_week] AND s.season = 2026`.\n"
        "- Strength of Schedule (SoS) / Matchup Difficulty:\n"
        "  1. Defensive Baseline: From `play_by_play` joined with `rosters`, compute average yards or fantasy points conceded by `defteam` against specific position groups (e.g., `r.position = 'WR'`).\n"
        "  2. Future Matchup Join: Join the player's upcoming `opponent_team` from `schedules` to the defensive baseline.\n"
        "  3. Ranking: Players/teams facing opponents with the highest average yards/points allowed have the 'easiest' remaining schedule.\n\n"
        "Relational Joins & SQL Rules:\n"
        "- `play_by_play` stores player IDs, not position abbreviations. To filter or aggregate plays by position (e.g., TE, WR, RB), join with `rosters` on `gsis_id`:\n"
        "    * Passing/Receiving: `JOIN rosters r ON p.receiver_player_id = r.gsis_id WHERE r.position = 'TE'`\n"
        "    * Rushing: `JOIN rosters r ON p.rusher_player_id = r.gsis_id WHERE r.position = 'RB'`\n"
        "- Defensive points/yardage conceded by position must aggregate `play_by_play.yards_gained` grouped by `defteam`.\n"
        "- Always filter out non-plays when calculating efficiency or EPA: `WHERE qb_kneel = 0 AND qb_spike = 0`.\n"
        "- Use `ILIKE '%Name%'` for player or team matching.\n"
        "- Format the final output clearly in Markdown using bold numbers, bullet points, or tables."   
    )

    config= types.GenerateContentConfig(
        system_instruction=system_instruction,
        tools=[run_sql_query],
        temperature=0.0
    )

    chat = ai_client.chats.create(
        model="gemini-3.5-flash-lite",
        config=config
    )

    # Automatic Function Calling (AFC) runs run_sql_query and returns the final synthesized answer
    response = chat.send_message(user_prompt)
    
    # Check if the model requested a function call
    if response.function_calls:
        for function_call in response.function_calls:
            name = function_call.name
            args = function_call.args
            
            if name == "run_sql_query":
                # Execute DuckDB query locally
                sql = args.get("sql_query")
                tool_result = run_sql_query(sql)
                
                # Send the database rows back to Gemini
                second_response = chat.send_message(
                    types.Part.from_function_response(
                        name=name,
                        response={"result": tool_result}
                    )
                )
                if second_response.text:
                    return second_response.text
    if response.text:
        return response.text

    # Candidate text fallback if response.text evaluates to None
    try:
        parts = response.candidates[0].content.parts
        text_parts = [p.text for p in parts if getattr(p, "text", None)]
        if text_parts:
            return "\n".join(text_parts)
    except Exception:
        pass

    return "No statistical summary could be generated."


# ---------------------------------------------------------
# Background Ingestion Task
# ---------------------------------------------------------
@tasks.loop(hours=24)
async def auto_refresh_db():
    """Runs once every 24 hours to check for and pull fresh nflreadpy data."""
    if ingest is None:
        print("[WARN] ingest.py not found; skipping scheduled DB refresh.", flush=True)
        return

    print("[INGEST-TASK] Running background database refresh...", flush=True)
    try:
        # Offload network download and DuckDB write to a separate thread
        await bot.loop.run_in_executor(None, ingest.refresh_nfl_duckdb)
        print("[INGEST-TASK] Background refresh finished successfully.", flush=True)
    except Exception as e:
        print(f"[INGEST-TASK ERROR] Failed to refresh database: {e}", flush=True)


# ---------------------------------------------------------
# Discord Command Handlers
# ---------------------------------------------------------
@bot.command(name="Hank2.0")
async def nfl_command(ctx: commands.Context, *, question: str):
    async with ctx.typing():
        try:
            # Run the query in executor to prevent blocking the async event loop
            answer = await bot.loop.run_in_executor(None, ask_gemini_with_duckdb, question)

            if not answer:
                answer = "No response generated."

            if len(answer) > 1950:
                file = discord.File(io.StringIO(answer), filename="nfl_stats.md")
                await ctx.reply("Response was too large for chat. Attached as file:", file=file)
            else:
                await ctx.reply(answer)
        except Exception as e:
            print("=== ERROR IN NFL COMMAND ===", flush=True)
            traceback.print_exc()
            print("============================", flush=True)
            await ctx.reply(f"**Error:** `{type(e).__name__}: {str(e)}`")


@bot.command(name="nflsync")
@commands.has_permissions(administrator=True)
async def manual_sync(ctx: commands.Context):
    """Admin command to force a manual database refresh from Discord."""
    if ingest is None:
        await ctx.reply("`ingest.py` module is not available in the bot container.")
        return

    await ctx.reply("Starting manual database sync with `nflreadpy`...")
    try:
        await bot.loop.run_in_executor(None, ingest.refresh_nfl_duckdb)
        await ctx.reply("✅ `nfl_stats.duckdb` successfully updated!")
    except Exception as e:
        await ctx.reply(f"❌ Sync failed: `{e}`")


@bot.event
async def on_ready():
    print(f"[READY] Logged in as {bot.user.name} (ID: {bot.user.id})", flush=True)

    # 1. Check if database exists; if not, trigger an initial ingestion
    if not os.path.exists(DB_PATH) and ingest is not None:
        print(f"[INIT] '{DB_PATH}' not found. Performing initial ingestion...", flush=True)
        await bot.loop.run_in_executor(None, ingest.refresh_nfl_duckdb)

    # 2. Start daily refresh loop
    if not auto_refresh_db.is_running():
        auto_refresh_db.start()


# ---------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------
if __name__ == "__main__":
    if not DISCORD_TOKEN:
        raise ValueError("Missing DISCORD_TOKEN environment variable.")
    if not GEMINI_API_KEY:
        raise ValueError("Missing GEMINI_API_KEY environment variable.")
    bot.run(DISCORD_TOKEN)